services:
  library:
    image: postgres:latest
    container_name: library
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    env_file: .env
    entrypoint: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    restart: unless-stopped


  proxy:
    image: mitmproxy/mitmproxy:latest
    container_name: proxy
    entrypoint: /bin/sh -c "chmod +x /home/mitmproxy/override.sh && /home/mitmproxy/override.sh"  
    env_file: .env
    ports:
        - "8888:8080"
    volumes:
        - ./proxy/addon.py:/home/mitmproxy/addon.py
        - ./proxy/override.sh:/home/mitmproxy/override.sh
    depends_on:
      - archiver
    restart: unless-stopped

  librarian:
    image: librarian:latest
    container_name: librarian
    env_file: .env
    build:
      context: .
      target: librarian
      dockerfile: Dockerfile.local
    volumes:
      - ./src/librarian:/app/src/librarian
    restart: unless-stopped

  archiver:
    image: archiver:latest
    container_name: archiver
    env_file: .env
    build:
      context: .
      target: archiver
      dockerfile: Dockerfile.local
    depends_on:
      - library
    volumes:
      - ./src/archiver:/app/src/archiver
    restart: unless-stopped

  worker:
    image: worker:latest
    container_name: worker
    env_file: .env
    build:
      context: .
      target: worker
      dockerfile: Dockerfile.local
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  data:
    driver: local
