"""adding processed to flow

Revision ID: bc3f6538db6f
Revises: ca1b13ede0dd
Create Date: 2025-05-14 18:47:36.938789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc3f6538db6f"
down_revision: Union[str, None] = "ca1b13ede0dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flows",
        sa.Column("processed", sa.Boolean(), nullable=False, server_default="f"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flows", "processed")
    # ### end Alembic commands ###
